site_name: Switchboard Docs
repo_name: deepal/switchboard
repo_url: https://github.com/deepal/switchboard
site_description: Open Source Mock Services Generator
edit_uri: edit/main/docs
theme:
  name: material
  features:
    - navigation.instant
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: teal
      accent: teal
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: teal
      accent: teal
markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
plugins:
  - tags:
      tags_file: tags.md
  - search
  - render_swagger
  - build_plantuml:
      render: 'server' # or "local" for local rendering
      bin_path: '/usr/local/bin/plantuml' # ignored when render: server
      server: 'http://www.plantuml.com/plantuml' # offical plantuml server
      disable_ssl_certificate_validation: true # for self-signed and invalid certs
      output_format: 'svg' # or "png"
      diagram_root: 'docs/diagrams' # should reside under docs_dir
      output_folder: 'out'
      input_folder: 'src'
      input_extensions: '' # comma separated list of extensions to parse, by default every file is parsed
extra:
  version:
    provider: mike
    default: latest
nav:
  - Introduction:
    - Overview: index.md
  - Mock Services:
    - REST Mock Services: mockservices/rest.md
    - Random Data Generation: mockservices/templating.md
  - Workspaces:
    - Introduction: workspaces/ws-intro.md
  - Importing:
    - Import Open API Spec: importing/openapi-import.md
  - Configuration API:
    - Setting up: api/setup.md
    - Mock Services: api/mock-services.md
    - Scenarios: api/mock-services.md
    - Workspaces: api/workspaces.md
    - Activity: api/activity.md
    - Authentication: api/auth.md
  - Tags 🏷: tags.md
  - Roadmap 🏁 : roadmap.md